remote("srk31", "https://github.com/stephenrkell/%.git")

repo("dwarfidl")
repo("liballocs")
repo("libantlr3cxx")
repo("libcrunch")
repo("libcxxfileno")
repo("libcxxgen")
repo("libdwarfpp")
repo("libmallochooks.hg", reponame="libmallochooks")
repo("libsrk31cxx")
repo("m4ntlr")
